### ISSUE TITLE
Debian 7 Installation Issue

### ISSUE THREAD

**Issue by ApfelUser** [ivaldi/brimir#145]
Hi, I am getting this error when installing Brimir:

**Command:**

`rake db:schema:load RAILS_ENV=production`

**Result:**

```
rake db:schema:load RAILS_ENV=production
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:34:in `block in setup'
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:19:in `setup'
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler.rb:122:in `setup'
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler/setup.rb:7:in `<top (required)>'
/srv/brimir/config/boot.rb:6:in `<top (required)>'
/srv/brimir/config/application.rb:1:in `<top (required)>'
/srv/brimir/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

Then I tried:

**Command:**

`bundle exec rake db:schema:load RAILS_ENV=production`

**Result:**

```
-- create_table("attachments", {:force=>true})
============= WARNING FROM mysql2 =============
The options :user, :pass, :hostname, :dbname, :db, and :sock will be deprecated at some point in the future.
Instead, please use :username, :password, :host, :port, :database, :socket, :flags for the options.
============= END WARNING FROM mysql2 =========
rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_handling.rb:87:in `connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:642:in `connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:655:in `block in method_missing'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:628:in `block in say_with_time'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:628:in `say_with_time'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:648:in `method_missing'
/srv/brimir/db/schema.rb:16:in `block in <top (required)>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/schema.rb:42:in `instance_eval'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/schema.rb:42:in `define'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/schema.rb:62:in `define'
/srv/brimir/db/schema.rb:14:in `<top (required)>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:171:in `load_schema_for'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:183:in `block in load_schema_current'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:223:in `block in each_current_configuration'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:222:in `each'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:222:in `each_current_configuration'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:182:in `load_schema_current'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/railties/databases.rake:238:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**My database.yml:**

```
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000
#
production:
  adapter: mysql2
  host: localhost
  database: support
  user: support
  password: <password>
```

**Comment by frenkel** [comment]
`Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)`

The database credentials are wrong, or the database does not exist. Can you connect using the command without problems?

`mysql -u support -p support`

**Comment by ApfelUser** [comment]
Yes, I can connect without problems using `mysql -u support -p support`
How do I solve `You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending 'bundle exec' to your command may solve this.` Also `Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)` doesn't seem like the problem is in the config, as it isn't even using the config.

**Comment by frenkel** [comment]
Using `bundle exec` doesn't matter, I use it sometimes as well. What happens if you try:

`RAILS_ENV=production bundle exec rake db:schema:load`

**Comment by ApfelUser** [comment]
Sorry for the late reply:

**Command:**

```
RAILS_ENV=production bundle exec rake db:schema:load
```

**Result:**

```
-- create_table("attachments", {:force=>true})
============= WARNING FROM mysql2 =============
The options :user, :pass, :hostname, :dbname, :db, and :sock will be deprecated at some point in the future.
Instead, please use :username, :password, :host, :port, :database, :socket, :flags for the options.
============= END WARNING FROM mysql2 =========
rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_handling.rb:87:in `connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:642:in `connection'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:655:in `block in method_missing'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:628:in `block in say_with_time'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:628:in `say_with_time'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:648:in `method_missing'
/srv/brimir/db/schema.rb:16:in `block in <top (required)>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/schema.rb:42:in `instance_eval'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/schema.rb:42:in `define'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/schema.rb:62:in `define'
/srv/brimir/db/schema.rb:14:in `<top (required)>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:171:in `load_schema_for'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:183:in `block in load_schema_current'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:223:in `block in each_current_configuration'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:222:in `each'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:222:in `each_current_configuration'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/tasks/database_tasks.rb:182:in `load_schema_current'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/railties/databases.rake:238:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Comment by frenkel** [comment]
Could you try editing the database.yml to fix this warning:

`The options :user, :pass, :hostname, :dbname, :db, and :sock will be deprecated at some point in the future.
Instead, please use :username, :password, :host, :port, :database, :socket, :flags for the options.`

**Comment by ApfelUser** [comment]
Okay, this worked:

**Command:**

```
RAILS_ENV=production bundle exec rake db:schema:load
```

**Result:**

```
-- create_table("attachments", {:force=>true})
   -> 0.0216s
-- add_index("attachments", ["attachable_id"], {:name=>"index_attachments_on_attachable_id"})
   -> 0.0163s
-- create_table("email_addresses", {:force=>true})
   -> 0.0073s
-- create_table("identities", {:force=>true})
   -> 0.0060s
-- add_index("identities", ["user_id"], {:name=>"index_identities_on_user_id"})
   -> 0.0140s
-- create_table("labelings", {:force=>true})
   -> 0.0070s
-- add_index("labelings", ["label_id", "labelable_id", "labelable_type"], {:name=>"unique_labeling_label", :unique=>true})
   -> 0.0169s
-- add_index("labelings", ["label_id"], {:name=>"index_labelings_on_label_id"})
   -> 0.0159s
-- add_index("labelings", ["labelable_id", "labelable_type"], {:name=>"index_labelings_on_labelable_id_and_labelable_type"})
   -> 0.0159s
-- create_table("labels", {:force=>true})
   -> 0.0068s
-- create_table("notifications", {:force=>true})
   -> 0.0066s
-- add_index("notifications", ["notifiable_id", "notifiable_type", "user_id"], {:name=>"unique_notification", :unique=>true})
   -> 0.0141s
-- add_index("notifications", ["notifiable_id", "notifiable_type"], {:name=>"index_notifications_on_notifiable_id_and_notifiable_type"})
   -> 0.0161s
-- add_index("notifications", ["user_id"], {:name=>"index_notifications_on_user_id"})
   -> 0.0157s
-- create_table("replies", {:force=>true})
   -> 0.0071s
-- add_index("replies", ["message_id"], {:name=>"index_replies_on_message_id"})
   -> 0.0169s
-- add_index("replies", ["ticket_id"], {:name=>"index_replies_on_ticket_id"})
   -> 0.0157s
-- add_index("replies", ["user_id"], {:name=>"index_replies_on_user_id"})
   -> 0.0159s
-- create_table("rules", {:force=>true})
   -> 0.0068s
-- create_table("status_changes", {:force=>true})
   -> 0.0065s
-- add_index("status_changes", ["ticket_id"], {:name=>"index_status_changes_on_ticket_id"})
   -> 0.0184s
-- create_table("tickets", {:force=>true})
   -> 0.0075s
-- add_index("tickets", ["assignee_id"], {:name=>"index_tickets_on_assignee_id"})
   -> 0.0202s
-- add_index("tickets", ["message_id"], {:name=>"index_tickets_on_message_id"})
   -> 0.0160s
-- add_index("tickets", ["priority"], {:name=>"index_tickets_on_priority"})
   -> 0.0159s
-- add_index("tickets", ["status"], {:name=>"index_tickets_on_status"})
   -> 0.0161s
-- add_index("tickets", ["user_id"], {:name=>"index_tickets_on_user_id"})
   -> 0.0154s
-- create_table("users", {:force=>true})
   -> 0.0074s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :unique=>true})
   -> 0.0164s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true})
   -> 0.0160s
-- initialize_schema_migrations_table()
   -> 0.0411s
```
 
But **`rake assets:precompile RAILS_ENV=production`** results in:

```
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:34:in `block in setup'
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:19:in `setup'
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler.rb:122:in `setup'
/usr/local/rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.8/lib/bundler/setup.rb:7:in `<top (required)>'
/srv/brimir/config/boot.rb:6:in `<top (required)>'
/srv/brimir/config/application.rb:1:in `<top (required)>'
/srv/brimir/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

Then I tried **`RAILS_ENV=production bundle exec rake assets:precompile`**, but this results in:

```
RAILS_ENV=production bundle exec rake assets:precompile
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = '774e48bcfa1eb2e4a66d09c61367b3afa287943c193c8463de85edf426c9bc48e902751e583c515b34eec9eb178c1803396dd85c552811aaac54fa5c0a415a5a'

Please ensure you restarted your application after installing Devise or setting the key.
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:480:in `raise_no_secret_key'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:209:in `devise_for'
/srv/brimir/config/routes.rb:3:in `block in <top (required)>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:344:in `instance_exec'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:344:in `eval_block'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:322:in `draw'
/srv/brimir/config/routes.rb:1:in `<top (required)>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/routes_reloader.rb:40:in `each'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/routes_reloader.rb:16:in `reload!'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:75:in `call'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:75:in `execute'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/routes_reloader.rb:27:in `updater'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application/finisher.rb:71:in `block in <module:Finisher>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
/srv/brimir/config/environment.rb:5:in `<top (required)>'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/srv/brimir/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

To which file do I have to add `config.secret_key = '774e48bcfa1eb2e4a66d09c61367b3afa287943c193c8463de85edf426c9bc48e902751e583c515b34eec9eb178c1803396dd85c552811aaac54fa5c0a415a5a'` now? 

Sorry for stealing your time, but I am new to Ruby on Rails :smile:

**Comment by frenkel** [comment]
Hi,

Sorry, that's a change I didn't add to the readme yet. You should create a file named `config/secrets.yml` which will be used to derive that secret_key file from.

First run `bundle exec rake secret` and then add the output to config/secrets.yml like so:

    production:
      secret_key_base: THEOUTPUTHERE

I'll create a bug report to add this to the `README`

**Comment by frenkel** [comment]
I just experienced the same `Mysql2::Error: Access denied for user 'root'@'localhost' ` error. You can fix it by using `username` instead of `user` in your database.yml
